### ISSUE TITLE
Regex is failing on hero ASHE

### ISSUE THREAD

**Issue by gutoxp** [spadevs/overwatch#9]
When apply the real_name regex on hero called ASHE is failing

**Comment by marcuxyz** [comment]
Okay, i believe that the next live we goes fixed this.

Thanks!!!!!!!!!!!!!!!!!!! 
@gutuxp

**Comment by marcuxyz** [comment]
I created this regex: `[[N|n]ome verdadeiro\:\s]?|(.+),.+:\s?(\d{1,3}|\w+)`. I believe it now works
